### ISSUE TITLE
スキーマを設計する

### ISSUE THREAD

**Issue by matsumatsu20** [haijima/quiz#12]
大枠は完成
https://docs.google.com/spreadsheets/d/1XJJJhOwqzr66QNJLMf65QHyZbgw7nB0XoSiav5QqTjU/edit?usp=sharing

【課題】
解答者の情報をDBに持たせるか、メモリで一時的に保存するのか

【終了条件】
・wikiに書く
・はいじまとけんけんの承認

**Comment by haijima** [comment]
スキーマ固まったらwikiに書いてほしいです！

**Comment by matsumatsu20** [comment]
現在RVフェーズです。
https://github.com/haijima/quiz/wiki/Schema

RV完了後クローズします

**Comment by haijima** [comment]
あ！REVIEW完了です！

**Comment by matsumatsu20** [comment]
あざっす！
