### ISSUE TITLE
APIのI/F設計

### ISSUE THREAD

**Issue by haijima** [haijima/quiz#13]
APIドキュメントを作ってください！

例を作ったので、ここに追記をお願いします。
https://github.com/haijima/quiz/wiki/API

一旦けんけんをasigneeにしました

【終了条件】
・wikiに作成
・はいじまとまっつんの承認

**Comment by kkoshijima** [comment]
ざっくりER図書きながら、APIで使いそうなメソッド書いていきました！
画像は一回ローカル落としてみてもらうほうが多分よいかと！

右矢印と左矢印はそれぞれ params と return です
params で、Event eventとかなってるところはそれに相当するものをJSONで渡すイメージ！
Admin Userのところだけ、passwordは別で扱う形に一旦しておきました。（別に必要ないかもだけど）
黄色くなってるのは、CRUDじゃない処理です。

あと、
answer_user → answerer
four_answers → choices
answerer_the_question → question_answerer
にそれぞれ変えちゃいました。

以上、よろしくどうぞ！

![er](https://cloud.githubusercontent.com/assets/7687824/6096154/0fe77794-afc6-11e4-91c4-37eef3333925.png)

**Comment by kkoshijima** [comment]
一応、もともとのxmindのファイルも添付しておく！

**Comment by kkoshijima** [comment]
間違えた！ｗ

**Comment by haijima** [comment]
一旦LGTMです！
進めていく上で変更等あれば適宜修正する方向で！
