### ISSUE TITLE
ユーザが自分の順位を画面で確認できること

### ISSUE THREAD

**Issue by haijima** [haijima/quiz#54]
### ゴール・目的

ユーザが結果発表時に、自分の順位をスマホの画面上で確認できるようにする。
自分が上位でなくとも、順位を知れるようにするため。（結果上位者は前に名前が映し出される）
### Doneの定義
- 画面に出す情報の精査ができている
  - 順位だけで良いか？
- 実装が終わっている
- UI（画面デザイン・文言など）の実装も終わっている

**Comment by isbtty** [comment]
これissues/53でやってしまった
